import { Inter } from 'next/font/google'
import './globals.css'
import DataProvider from './context/DataProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Giphy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DataProvider>
          {children}
        </DataProvider>
      </body>
    </html>
  )
}
